# # config file version
apiVersion: 1

datasources:
#   # <string, required> name of the datasource. Required
  - name: InfluxDB
#   # <string, required> datasource type. Required
    type: influxdb
#   # <string, required> access mode. direct or proxy. Required
    access: proxy
#   # <int> org id. will default to orgId 1 if not specified
#   orgId: 1
#   # <string> url
    url: http://influxdb:8086
#   # <string> database password, if used
    password: telegraf
#   # <string> database user, if used
    user: telegraf
#   # <string> database name, if used
    database: telegraf
#   # <bool> mark as default datasource. Max one per org
    isDefault: true