apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
  labels:
    app: ftps
spec:
  ports:
  - name: controlconnection
    port: 21
    protocol: TCP
    targetPort: 21
  - name: dataconnection
    port: 20
    protocol: TCP
    targetPort: 20
  - name: passive
    port: 2021
    protocol: TCP
    targetPort: 2021
  selector:
    app: ftps
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 2021
        volumeMounts:
        - name: ftps-volume
          mountPath: /home/ftps
      volumes:
      - name: ftps-volume
        persistentVolumeClaim:
          claimName: ftps-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi